name: Python Lint

on:
  push:
    branches: [main]
    paths:
      - uv.lock
      - pyproject.toml
      - blind_charging/**
      - tests/**
  pull_request:
    branches: [main]
    paths:
      - uv.lock
      - pyproject.toml
      - blind_charging/**
      - tests/**

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11"]

    steps:
      - uses: actions/checkout@v3

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: Set up Python3.x
        uses: actions/setup-python@v5
        id: py
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: uv sync --locked --all-extras --dev

      - name: Run linters
        run: uv run pre-commit run --all-files --show-diff-on-failure
